title: "A Sample Thesis"
subtitle: "With a Subtitle"
author: "Gordon Freeman"
institute: "Black Mesa"
date: now
date-format: long
lang: de

latex-auto-mk: true
bibliography: references.bib
number-sections: true
tbl-cap-location: bottom

project:
  output-dir: _output
  render:
    - main.qmd
  post-render:
    - _meta/purge_clutter_files.py
format:
    pdf:
        code-line-numbers: true
        include-in-header:
            text: |
                \usepackage{fancyhdr} % Footer & header
                \pagestyle{fancy} % Footer & header
                \fancyhead[R]{Black Mesa Research Facility} % Header right
execute:
    enabled: false
