title: "Meine Thesis"
subtitle: "Untertitel"
author: "Gordon Freeman"
institute: "Black Mesa"
date: now
date-format: long
lang: de

latex-auto-mk: true
bibliography: references.bib
number-sections: true
tbl-cap-location: bottom
csl: _meta/apa.csl

project:
  output-dir: _output
  render:
    - main.qmd
  post-render:
    - _meta/purge_clutter_files.py
format:
    pdf:
        code-line-numbers: true
        geometry:
            - left=30mm
            - top=30mm
            - right=25mm
            - bottom=25mm
        fontsize: 11pt
        mainfont: Arial
        sansfont: Arial # Title font
        linestretch: 1.5 # Line spacing
        monofont: "Courier New" # Code font
execute:
    enabled: false
